### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by jkirk** [geerlingguy/awx-container#46]
When starting `docker-compose up -d` I get some errors:

```
% docker logs docker-awx_awx_task_1                                     
/usr/bin/launch_awx_task.sh: line 8: /etc/tower/conf.d/environment.sh: No such file or directory                            
Using /etc/ansible/ansible.cfg as config file                                                           
127.0.0.1 | SUCCESS => {                                                                                               
    "changed": false,                                                                                      
    "elapsed": 2,                                                                                                         
    "path": null,                                                                         
    "port": 5432,                                                                                    
    "search_regex": null,                                                                                                                                                   
    "state": "started"                                                                           
}                                                                                                    
Using /etc/ansible/ansible.cfg as config file                                                        
127.0.0.1 | SUCCESS => {                                                                                        
    "changed": false,                                                                                        
    "elapsed": 0,                                                                                                   
    "path": null,                                                                                       
    "port": 11211,                                                                                                          
    "search_regex": null,                                                                                  
    "state": "started"                                                                                                 
}                                                                                     
Using /etc/ansible/ansible.cfg as config file                                                                             
127.0.0.1 | SUCCESS => {                                                                  
    "changed": false,                                                                                
    "elapsed": 1,                                                      
    "path": null,                                                                                    
    "port": 5672,                                                                     
    "search_regex": null,                                                                                       
    "state": "started"                       
}                                                                                                                   
Using /etc/ansible/ansible.cfg as config file               
127.0.0.1 | SUCCESS => {                                                                                                    
    "changed": false,                                                      
    "db": "awx"                                                                                                        
}                                                                          
Traceback (most recent call last):                                                                                        
  File "/usr/bin/awx-manage", line 11, in <module>                                        
    load_entry_point('awx==4.0.0.0', 'console_scripts', 'awx-manage')()                              
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 124, in manage
    prepare_env()                                                                                    
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 89, in prepare_env
    if not settings.DEBUG: # pragma: no cover                                                                   
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)                                                                                               
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)                                                                               
  File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")                                            
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Also, when visiting http://localhost I get an **Internal Server Error**.

**Comment by ajoldham** [comment]
I get this as well with trying many AWX docker-composes on GitHub.  Guessing some dependency changed and broke something?

**Comment by larsmaes** [comment]
I get this as well. Seems there are some config changes neede when going to version 4.0

**Comment by abradshaw** [comment]
Im also getting exactly this

**Comment by kquilliam** [comment]
Glad I am not alone on this one.

**Comment by PandyDev** [comment]
same for me

**Comment by PandyDev** [comment]
I fixed it by editing the image in the docker-compose file:


...
awx_web: 
    image: "geerlingguy/awx_web:latest"
    #image: "ansible/awx_web:latest"
....
awx_task:
    image: "geerlingguy/awx_task:latest"
    # image: "ansible/awx_task:latest"
...

**Comment by ajoldham** [comment]
Awesome, thx for sharing your container! :)

**Comment by ajoldham** [comment]
Awesome, thx for sharing your image! :)

**Comment by trotyoung** [comment]
> I fixed it by editing the image in the docker-compose file:
> 
> ...
> awx_web:
> image: "geerlingguy/awx_web:latest"
> #image: "ansible/awx_web:latest"
> ....
> awx_task:
> image: "geerlingguy/awx_task:latest"
> # image: "ansible/awx_task:latest"
> ...

thx, this fixed my issue.

**Comment by trickert76** [comment]
Hi Jeff, 
the above solution isn't really fixing the issue. Changing the image to yours on Docker hub means, that they/we use a awx Container image that is not updated over a year. We are talking about release v4 instead fo v1 (which is geerlingguy/awx_*).

Is it possible to get your Dockerfile and/or the scripts that generate the geerlingguy/awx_ container?

This would help to avoid installing "very" old versions of awx and maybe is a security risk at all.

**Comment by celson** [comment]
Just mount the volume in task and web container:

 volumes:
   - /tmp/SECRET_KEY:/etc/tower/SECRET_KEY

**Comment by ghost** [comment]
@celson What volumes are you mounting. Please be more specific with your fix.

**Comment by kitos9112** [comment]
Same issue here, unfortunately - Will see if adding volumes to the docker-compose.yml fixes it.

**Comment by kitos9112** [comment]
I did manage to copy over the required files to the running containers ("awx_web" & "awx_task") and then all I had to do is restarting them! up and running for the time being.

#> echo "aabbcc" > SECRET_KEY
#> docker cp SECRET_KEY <container_id>:/etc/tower/SECRET_KEY

I'm using vSphere Integrated Containers with docker-compose - I had to do the building part in my dev. environment and then push the images to Harbor. If anyone is interested in more details, PM me!

Good luck

**Comment by ebosveld** [comment]
I tried @kitos9112 fix, but I couldn't log in anymore. I changed the docker-compose.yml and added volumes to the missing files.

environment.sh
```bash
DATABASE_USER=awx
DATABASE_NAME=awx
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_PASSWORD='awxpass'
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
AWX_ADMIN_USER=admin
AWX_ADMIN_PASSWORD='password'
```

credentials.py
```python
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "awxpass",
        'HOST': "postgres",
        'PORT': "5432",
    }
}

BROKER_URL = 'amqp://{}:{}@{}:{}/{}'.format(
    "guest",
    "guest",
    "rabbitmq",
    "5672",
    "awx")

CHANNEL_LAYERS = {
    'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
                'ROUTING': 'awx.main.routing.channel_routing',
                'CONFIG': {'url': BROKER_URL}}
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '{}:{}'.format("memcached", "11211")
    },
    'ephemeral': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}
```

docker-compose.yml
```YAML
version: '3'
services:
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx

  rabbitmq:
    image: "rabbitmq:3"
    environment:
      RABBITMQ_DEFAULT_VHOST: awx

  memcached:
    image: "memcached:alpine"

  awx_web:
    # image: "geerlingguy/awx_web:latest"
    image: "ansible/awx_web:latest"
    links:
      - rabbitmq
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    volumes:
     - ./SECRET_KEY:/etc/tower/SECRET_KEY
     - ./environment.sh:/etc/tower/conf.d/environment.sh
     - ./credentials.py:/etc/tower/conf.d/credentials.py

  awx_task:
    # image: "geerlingguy/awx_task:latest"
    image: "ansible/awx_task:latest"
    links:
      - rabbitmq
      - memcached
      - awx_web:awxweb
      - postgres
    hostname: awx
    user: root
    volumes:
     - ./SECRET_KEY:/etc/tower/SECRET_KEY
     - ./environment.sh:/etc/tower/conf.d/environment.sh
     - ./credentials.py:/etc/tower/conf.d/credentials.py
```
