### ISSUE TITLE
Empty dir /var/lib/awx/public/static/

### ISSUE THREAD

**Issue by hbokh** [geerlingguy/awx-container#6]
Frontend is not working due to empty `/var/lib/awx/public/static/` in container `awx_web`.

Temporary (and ugly) workaround is entering the container and set a symlink:
```
docker exec -ti awxcontainer_awx_web_1 bash
cd /var/lib/awx/public
rm -rf static
ln -s /usr/lib/python2.7/site-packages/awx/ui/static
```

Anyway, thanks heaps for your work, Jeff! 🏆

**Comment by geerlingguy** [comment]
Ah, that could be why I seem to sometimes get errors with JS and CSS not loading as mentioned in https://github.com/geerlingguy/awx-container/issues/7 ...

Though it does work for me if I use the docker-compose.yml file as it currently exists :/

**Comment by geerlingguy** [comment]
Well, what do you know... switching to `user: root` in `docker-compose.yml` (in #7) and then running the above commands makes it so the UI works _and_ playbooks work.

Hmm, now how to best capture the changes above (at least for the short term!)?

**Comment by geerlingguy** [comment]
Maybe I'll just add a web_setup role that does:

```yaml
---
- name: Remove existing static assets folder.
  file:
    path: /var/lib/awx/public/
    state: absent

- name: Symlink awx UI folder into place.
  file:
    path: /var/lib/awx/public/static
    src: /usr/lib/python2.7/site-packages/awx/ui/static
    state: link
```

Going to test this now, hopefully I can get it working today!
